# Generated by Django 3.0.1 on 2020-05-17 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hor2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
