# Generated by Django 3.0.1 on 2020-05-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hor2', '0002_cities_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='city',
            new_name='name',
        ),
    ]
