# Generated by Django 3.0.1 on 2020-05-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hor2', '0003_auto_20200517_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='Horoscope',
        ),
    ]
