# Generated by Django 3.0.1 on 2020-05-17 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hor2', '0004_auto_20200517_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='hour',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='lat',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='lon',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='mint',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='tzone',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
