# Generated by Django 3.0.1 on 2020-05-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hor2', '0005_auto_20200518_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horoscope',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='horoscope',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='horoscope',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='horoscope',
            name='mint',
        ),
        migrations.RemoveField(
            model_name='horoscope',
            name='tzone',
        ),
    ]
